- name: variable
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com

  tasks:
    - name: Print variable
      ansible.builtin.debug:
        msg: URL - {{ URL }}
  #An ansible access variables with two flower brackets
    - name: print task variable
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: tasks.google.com
